
export const companiesService = {
  getCompanies,
}

async function getCompanies() {
  const companies = demoCompanies
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(_refactorCompanies(companies))
    }, 1000)
  })
}

function _refactorCompanies(companies) {
  return companies.map((company) => ({
    id: company.company_id,
    active: company.active,
    name: company.company_name,
    legalName: company.company_legal_name,
    country: company.country,
    dateAdded: company.date_added,
    isDpfFound: company.dpf_found,
    parentId: company.parent_id,
    providesAiServices: company.provides_ai_services,
  }))
}

// Raw company data
// "active": true,
// "company_id": "pAuC6RQ71bBG",
// "company_legal_name": "Market Data Insights LLC",
// "company_name": "Market Data Insights LLC",
// "country": "USA",
// "date_added": "Sun, 26 Jan 2025 16:54:36 GMT",
// "dpf_found": false,
// "parent_id": "hDQkIp9PldZO",
// "provides_ai_services": true

var demoCompanies = [
  {
    active: true,
    company_id: 'pAuC6RQ71bBG',
    company_legal_name: 'Market Data Insights LLC',
    company_name: 'Market Data Insights LLC',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:54:36 GMT',
    dpf_found: false,
    parent_id: 'hDQkIp9PldZO',
    provides_ai_services: true,
  },
  {
    active: false,
    company_id: 'sL4O0q46zTGJ',
    company_legal_name: 'TreSensa Technologies, Inc.',
    company_name: 'TreSensa Technologies, Inc.',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:54:37 GMT',
    dpf_found: false,
    parent_id: null,
    provides_ai_services: false,
  },
  {
    active: true,
    company_id: 'aRxlTZVm6Kr3',
    company_legal_name: 'Trialize Inc.',
    company_name: 'Trialize Inc.',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:54:35 GMT',
    dpf_found: false,
    parent_id: 'nm5sbfa3H1AU',
    provides_ai_services: true,
  },
  {
    active: true,
    company_id: 'hQPRqF23sFWr',
    company_legal_name: 'Zimmer Biomet Holdings, Inc.',
    company_name: 'Zimmer Biomet',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:38:24 GMT',
    dpf_found: true,
    parent_id: null,
    provides_ai_services: true,
  },
  {
    active: true,
    company_id: 'zS5p8AZDKHAy',
    company_legal_name: 'Priory Solutions LLC',
    company_name: 'Priory Solutions LLC',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:54:36 GMT',
    dpf_found: false,
    parent_id: 'hDQkIp9PldZO',
    provides_ai_services: true,
  },
  {
    active: true,
    company_id: 'hDQkIp9PldZO',
    company_legal_name: 'TRGRP, Inc.',
    company_name: 'TRGRP, Inc.',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:54:36 GMT',
    dpf_found: true,
    parent_id: null,
    provides_ai_services: true,
  },
  {
    active: true,
    company_id: 'nOLii2vnnMTf',
    company_legal_name: 'Treno, Inc.',
    company_name: 'Treno',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:54:37 GMT',
    dpf_found: false,
    parent_id: null,
    provides_ai_services: true,
  },
  {
    active: false,
    company_id: 'tAx3qMDrjrZi',
    company_legal_name: 'Trendline Interactive Holdings, LLC',
    company_name: 'Trendline Interactive Holdings, LLC',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:54:37 GMT',
    dpf_found: false,
    parent_id: null,
    provides_ai_services: false,
  },
  {
    active: true,
    company_id: 'dKhnUGcBrp3s',
    company_legal_name: 'ZipHQ, Inc.',
    company_name: 'ZipHQ, Inc.',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:37:59 GMT',
    dpf_found: true,
    parent_id: null,
    provides_ai_services: true,
  },
  {
    active: false,
    company_id: 'g2pvCB3qIzRs',
    company_legal_name: 'ZipGrade LLC',
    company_name: 'ZipGrade LLC',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:38:00 GMT',
    dpf_found: false,
    parent_id: null,
    provides_ai_services: false,
  },
  {
    active: true,
    company_id: 'wHcoH1EfthBT',
    company_legal_name: 'Zywave, Inc.',
    company_name: 'Zywave, Inc.',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:24:41 GMT',
    dpf_found: true,
    parent_id: null,
    provides_ai_services: true,
  },
  {
    active: true,
    company_id: 'j004dr5oc4HX',
    company_legal_name: 'Zyper Inc',
    company_name: 'Zyper Inc',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:24:42 GMT',
    dpf_found: false,
    parent_id: null,
    provides_ai_services: true,
  },
  {
    active: true,
    company_id: 'wZ7fnSNyny8U',
    company_legal_name: 'Zynga Inc.',
    company_name: 'Zynga',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:24:43 GMT',
    dpf_found: false,
    parent_id: null,
    provides_ai_services: true,
  },
  {
    active: false,
    company_id: 'q5xRMZERwO6M',
    company_legal_name: "Town's End Studios LLC",
    company_name: "Town's End Studios LLC",
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:24:43 GMT',
    dpf_found: false,
    parent_id: 'wZ7fnSNyny8U',
    provides_ai_services: false,
  },
  {
    active: true,
    company_id: 'kIBhSOdMH8US',
    company_legal_name: 'Rising Tide Games, Inc.',
    company_name: 'Rising Tide Games, Inc.',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:24:43 GMT',
    dpf_found: false,
    parent_id: 'wZ7fnSNyny8U',
    provides_ai_services: true,
  },
  {
    active: true,
    company_id: 'fJitPwzxnaEo',
    company_legal_name: 'PuzzleSocial, Inc.',
    company_name: 'PuzzleSocial, Inc.',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:24:44 GMT',
    dpf_found: false,
    parent_id: 'wZ7fnSNyny8U',
    provides_ai_services: true,
  },
  {
    active: true,
    company_id: 'wbqvkyXHLl08',
    company_legal_name: 'Spooky Cool Labs LLC',
    company_name: 'Spooky Cool Labs LLC',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:24:44 GMT',
    dpf_found: false,
    parent_id: 'wZ7fnSNyny8U',
    provides_ai_services: true,
  },
  {
    active: true,
    company_id: 'oT0ypIGOe79c',
    company_legal_name: 'Zylo',
    company_name: 'Zylo',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:24:44 GMT',
    dpf_found: false,
    parent_id: null,
    provides_ai_services: true,
  },
  {
    active: true,
    company_id: 'dBXlnpbGPpZ9',
    company_legal_name: 'Zwift, Inc',
    company_name: 'Zwift, Inc',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:24:45 GMT',
    dpf_found: false,
    parent_id: null,
    provides_ai_services: true,
  },
  {
    active: false,
    company_id: 'iT33B4uGCTqX',
    company_legal_name: 'Leeyo Software Inc.',
    company_name: 'Leeyo Software Inc.',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:24:45 GMT',
    dpf_found: false,
    parent_id: 'oiGMSMk2vNhr',
    provides_ai_services: false,
  },
  {
    active: true,
    company_id: 'sRqeq5uVVJHA',
    company_legal_name: 'Zephr US Inc.',
    company_name: 'Zephr US Inc.',
    country: 'USA',
    date_added: 'Sun, 26 Jan 2025 16:24:46 GMT',
    dpf_found: false,
    parent_id: 'oiGMSMk2vNhr',
    provides_ai_services: true,
  },
]
